# Generated by Django 2.2.7 on 2020-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweetmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('tweet_link', models.CharField(max_length=300)),
                ('tweet_date', models.CharField(max_length=300)),
                ('tweet_fav_count', models.CharField(max_length=300)),
                ('tweet_text', models.CharField(max_length=500)),
            ],
        ),
    ]
